# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 032055942bbe4ac0ace703d08bd9a82722af91c78cb49d53fa7fa0b645dae7ed0a18982ec1b7ed995f8b877032c7e7d5c0aeaba2dae236ac125d9aa3f6e4fa5a

test:
  secret_key_base: 73115709b8264512c1dfbb33851b4d6d2d3779049811f68133b0e95d2b3ac9d62fdfe9ef166782bc6e01f373a62412427f55b7342d9d4fcec2079c8df4ad5fa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
